/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_whole_jnidemo_MyActivity */

#ifndef _Included_com_whole_jnidemo_MyActivity
#define _Included_com_whole_jnidemo_MyActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_whole_jnidemo_MyActivity
 * Method:    hellojni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_whole_jnidemo_MyActivity_hellojni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
